name: (Template) Run Static Analysis

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Build Docker Test Container
        run: docker build --build-arg "COMPOSER_AUTH=${COMPOSER_AUTH}" -t php-docker -f ./docker/Dockerfile .
      -
        name: Boot Docker Test Container
        run: docker run -itd --name php-docker php-docker
      -
        name: Run Composer Install
        run: docker exec -i php-docker composer update --prefer-dist --no-interaction
      -
        name: Run Static Analysis
        run: docker exec -i php-docker composer run-tests
      -
        name: Tidy up
        run: docker stop php-docker && docker rm php-docker
