name: (Template) Run Static Analysis

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build Docker Test Container
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile
          tags: php-docker
          secrets: |
            "FOO=${{ secrets.FOO }}"
      -
        name: Check not-secret.txt value
        run: docker run -id php-docker cat not-secret.txt

      #     secrets: |
      #       "COMPOSER_AUTH=${{ secrets.COMPOSER_AUTH }}"
      # -
      #   name: Run Static Analysis
      #   run: docker run -id php-docker composer run-tests
